# Generated by Django 4.1.7 on 2023-02-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.everestkitchenpa.com/assets/images/menuShortCuts/momoShortCut.jpg', max_length=500),
        ),
    ]
